POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "title": "Limpar a casa"
}

###

GET http://localhost:3000/api/notes

###

GET http://localhost:3000/api/notes/6445cfebb572bb664b2d5880

###
DELETE http://localhost:3000/api/notes/6445cfebb572bb664b2d5880

###
PUT http://localhost:3000/api/notes/6445cfebb572bb664b2d5880
Content-Type: application/json

{
    "title": "fazer comida"
}